### ISSUE TITLE
I GET Failed to establish a new connection: [Errno 61] Connection refused

### ISSUE THREAD

**Issue by bibop** [john-adeojo/autogen_tutorial#1]
(base) bibop@BibopNewMacBook pyautogen % python SwarmAgents.py

PRINT SYS: /Users/bibop/.pyenv/versions/3.10.0/bin/python
models to use OpenAI:  ['gpt-3.5-turbo', 'gpt-3.5-turbo-16k', 'gpt-4-1106-preview', 'gpt-4']

chat_manager (to chat_manager):

How many Germans live in the colonial
holding in Aruba’s continent that was governed by Prazeres’s country? 

--------------------------------------------------------------------------------
[autogen.oai.completion: 11-13 00:20:14] {230} INFO - retrying in 10 seconds...
Traceback (most recent call last):
  File "/Users/bibop/.pyenv/versions/3.10.0/lib/python3.10/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/Users/bibop/.pyenv/versions/3.10.0/lib/python3.10/site-packages/urllib3/util/connection.py", line 95, in create_connection
    raise err
  File "/Users/bibop/.pyenv/versions/3.10.0/lib/python3.10/site-packages/urllib3/util/connection.py", line 85, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 61] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/bibop/.pyenv/versions/3.10.0/lib/python3.10/site-packages/urllib3/connectionpool.py", line 715, in urlopen
    httplib_response = self._make_request(
  File "/Users/bibop/.pyenv/versions/3.10.0/lib/python3.10/site-packages/urllib3/connectionpool.py", line 416, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/Users/bibop/.pyenv/versions/3.10.0/lib/python3.10/site-packages/urllib3/connection.py", line 244, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "/Users/bibop/.pyenv/versions/3.10.0/lib/python3.10/http/client.py", line 1276, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/Users/bibop/.pyenv/versions/3.10.0/lib/python3.10/http/client.py", line 1322, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/Users/bibop/.pyenv/versions/3.10.0/lib/python3.10/http/client.py", line 1271, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/Users/bibop/.pyenv/versions/3.10.0/lib/python3.10/http/client.py", line 1031, in _send_output
    self.send(msg)
  File "/Users/bibop/.pyenv/versions/3.10.0/lib/python3.10/http/client.py", line 969, in send
    self.connect()
  File "/Users/bibop/.pyenv/versions/3.10.0/lib/python3.10/site-packages/urllib3/connection.py", line 205, in connect
    conn = self._new_conn()
  File "/Users/bibop/.pyenv/versions/3.10.0/lib/python3.10/site-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x2ae8b5270>: Failed to establish a new connection: [Errno 61] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/bibop/.pyenv/versions/3.10.0/lib/python3.10/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/Users/bibop/.pyenv/versions/3.10.0/lib/python3.10/site-packages/urllib3/connectionpool.py", line 799, in urlopen
    retries = retries.increment(
  File "/Users/bibop/.pyenv/versions/3.10.0/lib/python3.10/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=1234): Max retries exceeded with url: /v1/chat/completions (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x2ae8b5270>: Failed to establish a new connection: [Errno 61] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/bibop/.pyenv/versions/3.10.0/lib/python3.10/site-packages/openai/api_requestor.py", line 606, in request_raw
    result = _thread_context.session.request(
  File "/Users/bibop/.pyenv/versions/3.10.0/lib/python3.10/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/bibop/.pyenv/versions/3.10.0/lib/python3.10/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/Users/bibop/.pyenv/versions/3.10.0/lib/python3.10/site-packages/requests/adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=1234): Max retries exceeded with url: /v1/chat/completions (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x2ae8b5270>: Failed to establish a new connection: [Errno 61] Connection refused'))

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/bibop/.pyenv/versions/3.10.0/lib/python3.10/site-packages/autogen/oai/completion.py", line 222, in _get_response
    response = openai_completion.create(**config)
  File "/Users/bibop/.pyenv/versions/3.10.0/lib/python3.10/site-packages/openai/api_resources/chat_completion.py", line 25, in create
    return super().create(*args, **kwargs)
  File "/Users/bibop/.pyenv/versions/3.10.0/lib/python3.10/site-packages/openai/api_resources/abstract/engine_api_resource.py", line 155, in create
    response, _, api_key = requestor.request(
  File "/Users/bibop/.pyenv/versions/3.10.0/lib/python3.10/site-packages/openai/api_requestor.py", line 289, in request
    result = self.request_raw(
  File "/Users/bibop/.pyenv/versions/3.10.0/lib/python3.10/site-packages/openai/api_requestor.py", line 619, in request_raw
    raise error.APIConnectionError(
openai.error.APIConnectionError: Error communicating with OpenAI: HTTPConnectionPool(host='localhost', port=1234): Max retries exceeded with url: /v1/chat/completions (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x2ae8b5270>: Failed to establish a new connection: [Errno 61] Connection refused'))

_**I'm getting this error even if I installed everything in a separated virtual environment. Any idea on how I can fix it?
Thanks a lot for the grat job you're doing!

Bibop Gresta**_

**Comment by john-adeojo** [comment]
Thanks for the feedback. Please could you provide a bit more context, where are you running this from? From first glance, it seems you're not able to connect to the OpenAI API. It has tried several times, hit the limit and then stopped. Are you working behind a firewall by any chance?
